name: Check production data
on: deployment_status
jobs:
  CheckProdData:
    # only runs this job on successful deploy and only for master
    if: ${{ github.event.deployment_status.state == 'success' && github.event.deployment_status.environment == 'Production' }}
    runs-on: ubuntu-latest
    steps:

      - name: Set commit in progress status
        run: |
          curl --request POST \
          --url https://api.github.com/repos/${{ github.repository }}/statuses/${{ github.sha }} \
          --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
          --header 'content-type: application/json' \
          --data '{
            "context": "CheckProdData",
            "state": "pending",
            "description": "Testing in progressâ€¦",
            "target_url": "https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
          }'

      - name: Checkout
        uses: actions/checkout@v1

      - name: Run Cypress
        id: cypress
        uses: cypress-io/github-action@v2
        with:
            spec: cypress/integration/prod.js
        env:
          CYPRESS_BASE_URL: ${{ github.event.deployment_status.target_url }}

      # https://docs.github.com/en/actions/reference/context-and-expression-syntax-for-github-actions#job-status-check-functions
      - name: Set commit final status
        if: always()
        # set the merge commit status check using GitHub REST API see https://docs.github.com/en/rest/reference/repos#create-a-commit-status
        run: |
          curl --request POST \
          --url https://api.github.com/repos/${{ github.repository }}/statuses/${{ github.sha }} \
          --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
          --header 'content-type: application/json' \
          --data '{
            "context": "CheckProdData",
            "state": "${{ steps.cypress.outcome }}",
            "description": "Tests finished: ${{ steps.cypress.outcome }}",
            "target_url": "https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
          }'